[versions]

#noinspection UnusedVersionCatalogEntry
binaryWrapper-version = "1.0.27"

#noinspection UnusedVersionCatalogEntry
elementum-versionCode = "99"

#noinspection UnusedVersionCatalogEntry
lt2http-versionCode = "43"

# https://developer.android.com/tools/releases/build-tools
#noinspection UnusedVersionCatalogEntry
buildToolsVersion = "36.1.0"

# https://developer.android.com/tools/releases/platforms
#noinspection UnusedVersionCatalogEntry
compileSdk = "36"
#noinspection UnusedVersionCatalogEntry
minSdk = "26"

# https://developer.android.com/ndk/downloads
#noinspection UnusedVersionCatalogEntry
ndkVersion = "29.0.14206865"

# https://developer.android.com/ndk/guides/cmake
#noinspection UnusedVersionCatalogEntry
cmake = "4.1.2"

# https://developer.android.com/ndk/guides/cpp-support
#noinspection UnusedVersionCatalogEntry
cpp = "17"

[libraries]

# https://mvnrepository.com/artifact/androidx.test/runner
androidTest-runner = { module = "androidx.test:runner", version = "1.7.0" }

# https://mvnrepository.com/artifact/androidx.test.ext/junit-ktx
androidTest-junit = { module = "androidx.test.ext:junit-ktx", version = "1.3.0" }

# https://mvnrepository.com/artifact/junit/junit
test-junit = { module = "junit:junit", version = "4.13.2" }

[plugins]

# https://mvnrepository.com/artifact/com.android.tools.build/gradle
android-application = { id = "com.android.application", version = "9.0.0" }
android-library = { id = "com.android.library", version = "9.0.0" }

# https://mvnrepository.com/artifact/com.github.breadmoirai.github-release/com.github.breadmoirai.github-release.gradle.plugin
github-release = { id = "com.github.breadmoirai.github-release", version = "2.5.2" }
